apiVersion: apps/v1
kind: Deployment
metadata:
  name: item-service
  labels:
    app: item-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: item-service
  template:
    metadata:
      labels:
        app: item-service
    spec:
      containers:
      - name: item-service
        image: yourrepo/item-service:1.0.3
        ports:
        - containerPort: 6001
        env:
        - name: spring.application.name
          value: "item-service"
        - name: eureka.client.service-url.defaultZone
          value: "http://eurekaserver:8761/eureka/"
        - name: spring.datasource.url
          value: "jdbc:mysql://mysql:3306/dbecommerce_item?useSSL=false&serverTimezone=UTC"
        - name: spring.datasource.username
          value: "root"
        - name: spring.datasource.password
          value: "root_password"