apiVersion: v1
kind: ConfigMap
metadata:
 name: prometheus-config
 labels:
   app: prometheus
data:
 prometheus.yml: |
   global:
     scrape_interval: 15s
   scrape_configs:
     - job_name: 'api-gateway'
       static_configs:
         - targets: ['api-gateway:6000']


     - job_name: 'item-service'
       static_configs:
         - targets: ['item-service:6001']


     - job_name: 'payment-service'
       static_configs:
         - targets: ['payment-service:6003']


     - job_name: 'user-service'
       static_configs:
         - targets: ['user-service:6002']


     - job_name: 'node'
       static_configs:
         - targets: ['node-exporter:9100']